import '@fortawesome/fontawesome-svg-core/styles.css';
import '../styles/globals.css'
import { Comfortaa } from 'next/font/google'

const comfortaa = Comfortaa({ subsets: ['latin'] });

export const metadata = {
  title: 'LowScarlet - Personal Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="forest">
      <body className={comfortaa.className}>
        {children}
      </body>
    </html>
  )
}
